apiVersion: v1
kind: Service
metadata:
  name: task-tracker-svc
  labels:
    app: task-tracker
spec:
  ports:
    - port: 80
      targetPort: 8000
      name: http
  selector:
    app: task-tracker
  type: NodePort