apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-tracker
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0%
  selector:
    matchLabels:
      app: task-tracker
  template:
    metadata:
      labels:
        app: task-tracker
    spec:
      containers:
        - name: task-tracker
          image: IMAGE
          livenessProbe:
            failureThreshold: 3
            exec:
              command:
              - bash
              - -c
              - "curl --location --request GET 'http://0.0.0.0:8001/health' --header 'x-api-key: ${API_KEY}'"
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            exec:
              command:
              - bash
              - -c
              - "curl --location --request GET 'http://0.0.0.0:8001/health' --header 'x-api-key: ${API_KEY}'"
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 1
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 400m
              memory: 400Mi
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - containerPort: 8000
