name: Terraform Deploy

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.7

    - name: Create temporary SSH public key file
      run: |
        echo "${{ secrets.SSH_PUBLIC_KEY }}" > temp_ssh_key.pub

    - name: Terraform Init
      run: terraform init

    - name: Terraform Format Check
      run: terraform fmt -check -recursive

    - name: Terraform Validate
      run: terraform validate

    - name: Terraform Plan
      run: terraform plan -detailed-exitcode -lock=true -var="public_key_path=temp_ssh_key.pub" -out terraform-infra.tfplan

    - name: Terraform Apply
      if: github.event_name == 'workflow_dispatch'
      run: terraform apply -lock=true -input=false terraform-infra.tfplan
